### PR TITLE
Shannon frontend

### PR DESCRIPTION
**Pull request by shanhix1-personal**
Added a few components to frontent in app.component. We will need to rearrange where some of these components live when we introduce new pages (like recipes, meal plan, etc.), but this is a start. Also, for some reason the images sometimes show up and sometimes don't. I'm not sure why that is, so I need to investigate. 

Future work (will become GitHub issues): 
Clear inputs when entered for login/register
Create new pages and routings for recipes / meal plan / grocery list pages
Move components from app.components to the respective appropriate pages
Populate cards with data from backend
Populate cards dynamically
Debug image issue...

### CODE REVIEW

**Comment by shanhix1-personal** [comment]
Screenshots of new additions:

image

After clicking on datepicker:

image

**Comment by Em-Anderson** [comment]
Looks good to me! I can investigate some of the image loading issues as well tomorrow when I sit down to work on this.

**Review by sethyboy20 — APPROVED** [review]
looks good

**Comment by wejama** [comment]
Approved!

**Review by wejama — APPROVED** [review]

**Pull request merged**
